Fix Massachusetts scraper
d4bl/COVID19_tracker_data_extraction pull request #179
Opened 2021-01-15 08:16 UTC by fredtsun

Fixes #165 

I think they changed this from a zip file of csvs to a single spreadsheet and 
they also changed some field names.

This change now downloads a spreadsheet and has some changes for the
renamed field names.

2021-01-16 21:45 UTC, nkrishnaswami requested changes
Looks good! Tiny spelling fix, and it's good to go from my side.

2021-01-16 21:45 UTC, nkrishnaswami commented on workflow/python/covid19_scrapers/states/massachusetts.py
> +    """Massachusetts publishes a xlsx file containin COVID-19
sp: containing

2021-01-17 01:52 UTC, fredtsun commented on workflow/python/covid19_scrapers/states/massachusetts.py
> +    """Massachusetts publishes a xlsx file containin COVID-19
opps, ty!

2021-01-17 03:48 UTC, nkrishnaswami approved these changes

2021-01-17 04:21 UTC, merged